"""removed repetition in category + mini fix for b_change foreign keys

Revision ID: 918eae80e064
Revises: 228e06e5d15a
Create Date: 2025-07-14 19:09:42.777068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '918eae80e064'
down_revision: Union[str, Sequence[str], None] = '228e06e5d15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_changes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('categories', 'repetition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('repetition', postgresql.ENUM('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='repetitiontype'), autoincrement=False, nullable=True))
    op.alter_column('balance_changes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
